application: udacity-blog-1067
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /templates/css
  static_dir: templates/css

- url: .*
  script: udacity-blog-1067.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest